### ISSUE TITLE
Issue launching application

### ISSUE THREAD

**Issue by okoeth** [sashamitrovich/MarkLogic-k-dashboard#2]
After successful installation, I can login, but then I get:
XDMP-OBJCONSTRUCTCHILDSEQ: $day-winner/stock/Name/text() -- Object nodes cannot have sequence children: name . See the MarkLogic server error log for further detail.
Any idea what went wrong? Server logs did include any further suggestions...

**Comment by sashamitrovich** [comment]
Need to import data - it's failing because the stock data is expected to be in the DB already. Check the README.MD for instructions on loading data.

Alternatively, you can switch off the stock indicators on the /config page and the problem will go away even if you don't have stock data. 

Does this help?

**Comment by okoeth** [comment]
Yes, problem solved. Thx.
